### ISSUE TITLE
Mid-term presentation

### ISSUE THREAD

**Issue by rauldds** [rauldds/Hyperspectral_CT_Recon#12]
Content:
- Describe Hyperscpectral/Dual CT (What is novel about it)
- The problem
- What we want to do
- Related work
- Our Plan/Timeline
- Current status (with visualization)
-  What we plan to have by the end

**Comment by luisdavid64** [comment]
Niko's feedback on presentation
1. An image might help to explain what hyperspectral CT/imaging means physically and why it is beneficial to understand material properties compared to single energy measurments e.g. https://en.wikipedia.org/wiki/X-ray_absorption_spectroscopy or you could also show a spectrum of a pixel/voxel from the MUSIC dataset
2. Add full references ([all authors, title, publication, year] in any order) directly on the slides e.g. for MUSIC
3. It might help to clarify what is your input and what is your output e.g. working on sinograms, slices, 3d, etc.
4. Introduce acronyms and background e.g. FBP, unmixing, etc.
5. In your plan you mention CT reconstruction, if you want to work on it it might also be good to add it to the related work and give some background
6. Highlighting the hyperspectral related differences compared to other approaches might also help to point out the modifications that need to be done
7. MUSIC dataset details to train the method might also be useful to understand the data situation better
8. A more detailed description of the experiments e.g. related to "Object shape vs. hyperspectral “texture” for materials." could be interesting, too
